from typing import Protocol
from aichat.domain.entities import User, Channel, Message


class ChatUseCase(Protocol):
    @property
    def default_channel(self) -> str: ...
    
    def connect(self, nickname: str, is_agent: bool = False) -> User: ...
    def disconnect(self, user: User) -> None: ...
    def join(self, user: User, channel_name: str) -> Channel: ...
    def leave(self, user: User, channel_name: str) -> None: ...
    def post_message(self, user: User, channel_name: str, text: str) -> Message: ...
    def list_channels(self) -> list[str]: ...