from typing import Protocol
from aichat.domain.entities import User, Message, Channel


class Notifier(Protocol):
    def user_joined(self, user: User, channel: Channel) -> None: ...
    def user_left(self, user: User, channel: Channel) -> None: ...
    def message_posted(self, message: Message, channel: Channel) -> None: ...